name: Docker Build

on:
#  schedule:
#    - cron: "30 4 * * *"
  push:
    branches: ["dev"]

jobs:
  build:
    strategy:
      fail-fast: false
      #     max-parallel: 2
      matrix:
        version: ["ms-admin"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login cn-hangzhou
      - name: Login Into HangZhou
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: "registry.cn-hangzhou.aliyuncs.com"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push
        uses: docker/build-push-action@v4
        with:
          context: ruoyi-admin
          platforms: linux/amd64
          push: true
          file: Dockerfile
          tags: |
            registry.cn-hangzhou.aliyuncs.com/okami/docker-php:${{ matrix.version }}
